package de.wobkenh.pgen

import java.io.File
import java.time.LocalDateTime

object PumlWriter {

    private val newLine = PGenConstants.newLine

    fun writePuml(
        pumlBodyString: String,
        packagePath: String,
        attributeVisibility: Visibility,
        methodVisibility: Visibility,
        scale: String?,
        title: String?,
        caption: String?,
        leftToRightDirection: Boolean,
        outputFile: File
    ) {
        val headerLines = mutableListOf(
            "@startuml",
            "/'",
            "    PUML Class Diagram generated by PGen",
            "    Date: ${LocalDateTime.now()}",
            "    Package: $packagePath",
            "'/"
        )
        if (attributeVisibility == Visibility.NONE && methodVisibility == Visibility.NONE) {
            headerLines.add("hide members")
        }
        if (scale != null) {
            headerLines.add("scale $scale")
        }
        if (title != null) {
            headerLines.add("title $title")
        }
        if (caption != null) {
            headerLines.add("caption $caption")
        }
        if (leftToRightDirection) {
            headerLines.add("left to right direction")
        }
        val footer = "@enduml"
        outputFile.writeText(listOf(headerLines.joinToString(newLine), pumlBodyString, footer).joinToString(newLine))
    }
}